# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Common
javaVersion=24
minecraftVersion=1.21.11
minecraftDisplayVersion=1.21.11

# Fabric
fabricLoaderVersion=0.18.4
fabricVersion=0.140.2+1.21.11
fabricMinecraftVersionRange=~1.21.11
# ~1.x.1 <-> 1.x.1, 1.x.2, ...

# Forge
#forgeVersion=61.0.3
#forgeVersionRange=[53,)
#forgeMinecraftVersionRange=[1.21.2,1.21.11)
